### ISSUE TITLE
Tag on failure

### ISSUE THREAD

**Issue by zominym** [theangryangel/logstash-output-jdbc#107]
Hi,

I am using your plugin to output data into a Postgre DB, and it works great, thank you for that!

I was wondering if there was any method to detect an exception occurred when outputting using your plugin? Like the "_dissectfailure", "_jsonfailure" or "_grokfailure" tags for example, or another method.

(say I get the following exception for example: `:exception=>org.postgresql.util.PSQLException: ERROR: invalid input syntax for integer: ""`)

Regards.

**Comment by theangryangel** [comment]
I'll prefix the statement by saying I've not been keeping up with Logstash's development very closely for the last year, especially the last few months as I've had a lot going on outside of work, so forgive me if I've missed a feature that I'm not aware of.

Tags make sense for inputs and filters because you can start taking other actions if something has gone wrong. With an output plugin once an event has hit an output it doesn't go back into the event pipeline - in effect the tagging wouldnt go anywhere else and wouldnt allow you to do anything with it.

Again if this has changed, or I've missed that logstash can do this (in which case I need to look at altering the plugin to support this).

**Comment by zominym** [comment]
Hey!

Thanks for the quick answer.

No problem, I was wondering if you knew any other way I could do that with your framework.

As for the tag, even if you can't filter anymore, you can still ad another output after this one, so that if the tag is present after the JDBC output, you can also output it in a file containing specifically errored querries or so.

**Comment by theangryangel** [comment]
I'm pretty sure that outputs are executed simultaneously by logstash, unlike filters which are processed in the order of definition. This means adding a tag doesnt work for the scenario you want. But I've never actually checked nor had to a need to check until now.. I'll try and find some time to check later to see if I'm right. The docs arent clear and I dont really want to go looking through the logstash core source.

It appears v6 adds dead letter support for the elasticsearch output only, with a note that future versions of logstash may support this for other output plugins.
