### ISSUE TITLE
Insert into multiple tables? 

### ISSUE THREAD

**Issue by wroberts15** [theangryangel/logstash-output-jdbc#27]
Pretty simple question, however I'm stuck (maybe because it's the end of the day):

Basically, can I have multiple statements or multiple "INSERT INTO"'s in one statement? Doesn't seem to be working for me right now. Below is my configuration (keep in mind that I have it working inserting into one table)

```
connection_string => 'jdbc:sqlite:myexample.db'
statement => [ "INSERT INTO req(filename, cval, querystring, datestring, ref_hash, ua_hash) VALUES(?,?,?,?,?,?); INSERT INTO reflookup(refhash,referrer) VALUES(?,?); INSERT INTO ualookup(uahash,useragent) VALUES(?,?);", "%{name}", "%{cval}", "%{querystring}", "%{datestring}", "%{refhash}", "%{uahash}", "%{refhash}", "%{ref}", "%{uahash}", "%{useragent}"]
```

I apologize if I missed something in the README or something similar. 
BTW, great plugin it's been pretty simple and useful.

**Comment by theangryangel** [comment]
The statement parameter is assumed to be a single SQL command (at the moment), which isn't really particularly easy to workaround since most JDBC drivers will only permit a single SQL command in a prepared statement :disappointed: 

That said, some JDBC drivers do have support for multiple queries - MySQL for example supports  allowMultiQueries=true in the connection string.

I don't know of any parameter which would work for sqlite though.

However, a workaround would be to have multiple JDBC outputs, using the same details but with 2 different statements. That should work without any problems, and without modifying the plugin. It's not ideal, but if you're generating your configuration dynamically then it wouldnt be much extra hassle.

**Comment by wroberts15** [comment]
Okay cool, that should work for my needs most likely. Taking the next few days off (thankfully) but I can update this thread when I've tried it out.. should work though. Thanks

**Comment by wroberts15** [comment]
yea this is working.. thanks again
