### ISSUE TITLE
Unable to connect to database when connection string uses TCPS.

### ISSUE THREAD

**Issue by shravan521** [theangryangel/logstash-output-jdbc#43]
I am using ojdbc6.jar driver along with jre1.8 while trying to connect to a database instance. The connection string uses TCPS protocol which is referring to Sha1 certificate.
Now as per our new rules we had to use Sha2 certificate for secured connections. I have imported the new certificate into my cacerts. And the plugin is not able to connect to database anymore. 
Is it something that we have to fix here.
We have tried using 
jre1.7 and ojdbc7.jar to check the compatibility. But didn't work.
Is it possible to use Weblogic data source in place of connection string. Which would resolve my issue.

Thanks,
Shravan

**Comment by theangryangel** [comment]
Can you try running logstash with the --debug flag. You should get a lot more information about the connection error.

Can you also confirm what version of the plugin and logstash you're running as well?

Unfortunately I have 0 experience with Oracle and it's associated products, so some of this will be a learning experience for me. 

My gut feeling is that since this plugin is very simple (it is a very thin wrapper around JDBC), if you were able to connect before the certificate was switched then it's likely either a mis-configuration, or something else has also changed, not just the certificate.

**Comment by shravan521** [comment]
[logstash.out.zip](https://github.com/theangryangel/logstash-output-jdbc/files/328138/logstash.out.zip)

Thanks a lot for the quick response. I have attached a zip file of logstash.out after running the logstash with debug flag. You will have to unzip and then untar as well to view the file.

logstash version is 2.1.0 and the plugin version is 0.2.1.

I have verified by removing the TCPS and using TCP the same settings works fine. TCPS with Sha1 also works fine, only TCPS with Sha2 certificate is failing.

**Comment by theangryangel** [comment]
Can you try upgrading to 0.2.7 of the plugin? `bin/plugin update logstash-output-jdbc` from the installation directory should do it. 0.2.7 *should* work with 2.1.0 without problems (although I've not tested it).

My reasoning is that 0.2.1 was the first version with the connection pooling and there was a flaw with the default connection timeout which was fixed in a later version that threw that same exception.

I'm guessing that it's taking slightly longer to connect and you may be hitting that same bug.

**Comment by shravan521** [comment]
Thanks a lot. I have increased the connection timeout to 10000 and it started working.
I will upgrade it to 0.2.7 soon.

**Comment by theangryangel** [comment]
:+1: No problem.

Really do recommend the upgrade though :smile:

**Comment by shravan521** [comment]
Sure.  I will upgrade it soon.
