### ISSUE TITLE
Validation failed for <field_name>: 'NULL' cannot be cast to type double

### ISSUE THREAD

**Issue by Archith09** [theangryangel/logstash-output-jdbc#52]
I am using logstash 2.3.1 version. Input plugin is elasticsearch and I am trying to insert data into crate.io database using logstash output jdbc plugin.
There is a field 'M_body_t', of type DOUBLE, which has both integer values and null values from source. When the below config is run, it throws an error 'Validation failed for bench_pose_m_body_t: 'NULL' cannot be cast to type double'.

input{
 elasticsearch {
   hosts => "host_name:9200"
   index => "index1"
   query => '{ "size":10,"query": {"match_all": {} } }'
 }
}
filter{
        if!([bench_pose][M_Body_t]) {
                mutate{
                        add_field => {"[bench_pose][M_Body_t]" => "NULL"}
                }
        }
        if!([bench_pose][M_Jaw_t]) {
                mutate{
                        add_field => {"[bench_pose][M_Jaw_t]" => "NULL"}
                }
        }
}
output{
 jdbc {
       driver_class => "io.crate.client.jdbc.CrateDriver"
       driver_auto_commit => false
       driver_jar_path => "/path/to/crate-jdbc-standalone-1.12.3.jar"
       connection_string => "crate://host_ip:4300"
       statement => ["INSERT INTO chartd_ls(path,bench_pose_m_Body_t,bench_pose_m_jaw_t) VALUES(?,?,?)",'path','%{[bench_pose][M_Body_t]}','%{[bench_pose][M_Jaw_t]}']
   }
}

If I remove the filter plugin, then I am facing an error 'Validation failed for <field_name>: '%{[bench_pose][M_Body_t]}' cannot be cast to type double', when the source has null value.

I know DOUBLE datatype does not allow null values to be inserted but how do I retain NULL values in these fields in the destination table?

**Comment by theangryangel** [comment]
Since I don't recognise that error, I'd guess that's the crate.io jdbc driver or crate.io itself throwing that error? (One reason why I ask for the complete error/log is so that I don't have to guess)

I don't have experience with crate.io, so frankly I don't know what the answer is, without spending time looking at their documentation. 

In most sql engines you can create fields that permit bulls by just not specifying `not null` in the table definition. Presumably there's an equivalent for crate.io and you've specified that on the table?
