### ISSUE TITLE
RangeError: too big for int

### ISSUE THREAD

**Issue by seamy49** [theangryangel/logstash-output-jdbc#61]
Hi, 

Im using version 2.x of the plugin and Im trying to load in a value 4000881632477184 which is 16 digits long, I am using a mySql db and have defined the column as BigInt, so it should hold the field. The plugin returns the output below;
JDBC - Exception. Not retrying. {:exception=>RangeError: too big for int: 4000881632477184

Is the plugin limited to a 10 digit int field? 

Im running logstash 2.1.1

Thanks

**Comment by theangryangel** [comment]
Right now the plugin doesn't have any knowledge of anything other than int, so it's probably freaking out over this line https://github.com/theangryangel/logstash-output-jdbc/blob/master/lib/logstash/outputs/jdbc.rb#L278

It should be easy enough to patch. I'm hoping to have some time over the coming weekend and I'll see if I can work out a patch and a release to address this for you.

As an aside I'm sorry if I come across as a dick, but 2.x isn't a helpful identifier. There's the 2.x branch, but from that there's been 10 releases. Some of them with some serious bugs which were yanked (_unreleased_) from rubygems. I generally ask for the actual version number you're running because I've wasted time looking into stuff that was fixed months ago and people don't upgrade.

**Comment by seamy49** [comment]
Thanks for quick reply, plugin info;
logstash-output-jdbc (0.3.1)

**Comment by theangryangel** [comment]
Thanks @seamy49. I am sorry if I've come across a bit grumpy this morning. 

Probably not enough coffee yet 😨  I'll let you know when I've got a fix and released it 😄 Should be in a day or two

**Comment by seamy49** [comment]
Great @theangryangel, cheers.

**Comment by theangryangel** [comment]
Turns out it was easy enough to deal with this one during a coffee break.

I've push 0.3.2 to rubygems. You should be able to upgrade the plugin and it should work.

For my future reference: 
 - Need to apply this patch to the master branch
 - Travis is reporting the  2.x branch as failing due to #55, but it is again fine on my test boxes

**Comment by seamy49** [comment]
Thanks for speedy response and turnaround @theangryangel 
plugin updated to 0.3.2 and is working now for BigInt.

**Comment by casieo** [comment]
Hi, I'm getting this same error ("too big for int").  I see that updating the plugin resolved it for seamy49.  How do I update the plugin?  After some trial and error, I decided to try the attached, but it's been at this point for over 20 minutes.  The initial install took seconds.
![updatelogstashjdbcplugin](https://cloud.githubusercontent.com/assets/14110178/19457761/aa728050-947c-11e6-8098-fa351d749c1b.JPG)

**Comment by theangryangel** [comment]
Your screenshot suggests that you're using logstash 1.5? That is too old for this fix, as its only contained in the versions that support 2 and 5. You need to upgrade logstash itself (I'm sorry but I don't have the time to maintain the plugin for 3 versions of logstash, especially for 1.5 as elastic doesn't release updates for 1.5 any more either)

**Comment by casieo** [comment]
ok, that works.  Thanks!
