### ISSUE TITLE
Support for FF in millis

### ISSUE THREAD

**Issue by metinha** [theangryangel/logstash-output-jdbc#68]
Is there any posiblity to add support to FF format for milliseconds (like HH24:MI:SS.FF6), please?

**Comment by theangryangel** [comment]
Just to warn you, I've found JDBC driver support of timestamps to be one of the more annoying things to deal with in this plugin. It would be polite to say it's inconsistent. 

There are 2 options we can try:

1. Either we implement a configuration option for a custom strftime formatting string - this will depend on whatever JDBC endpoint you're using as to whether or not it'll work
2. Provide a configuration option to use setTimestamp instead of formatting the timestamp to a string, and hope your JDBC driver works properly

Let me know what JDBC driver you're using, and an example table and I'll see what works.

**Comment by metinha** [comment]
We use ORACLE as a JDBC endpoit where we have this need and just add the support for the formating with TO_DATE(?, 'dd/mm/yyyy hh24:mi:ss.FF5') instead of just TO_DATE(?, 'dd/mm/yyyy hh24:mi:ss')

**Comment by theangryangel** [comment]
The most recent versions for Logstash v5 and v2 should already be outputting milliseconds (between 000...999) (see https://github.com/theangryangel/logstash-output-jdbc/blob/master/lib/logstash/outputs/jdbc.rb#L17).

What version of Logstash and what version of the plugin are you using, please? I highly recommend the latest version of the plugin if you're on Logstash v2, and I highly recommend you're on at least Logstash 2.3.

**Comment by metinha** [comment]
We are using Logstash 2.4, so as far as I can remember it is compatible with 5 api. We'll upgrade to the latest version. Thank you so much for your time!

**Comment by theangryangel** [comment]
If you find it's still not working after upgrading let me know and I'm happy to take a look at it when I have a moment.
