### ISSUE TITLE
JDBC output plugin is shutting down the application 

### ISSUE THREAD

**Issue by NavneetMathpal** [theangryangel/logstash-output-jdbc#75]
Hi ,

I was using JDBC output for pushing my logs to database . It was running fine but after a week , logstash stops running automatically . as I had checked the logs I am getting below error 

 :LNonTransientConnectionExceMySQLNonTransientConnectionExce:message=>"JDBC - Exception repeated more than the maximum configured", :exception=>com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransien
tConnectionException: No operations allowed after connection closed., :max_repeat_exceptions=>5, :max_repeat_exceptions_time=>30, :level=>:error}
E492: Not an editor command: LNonTransientConnectionExceMySQLNonTransientConnectionExce:message=>"JDBC - Exception repeated more than the maximum configured", :exception=>com.mysql.jdbc.excep
tions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed., :max_repeat_exceptions=>5, :max_repeat_exceptions_time=>30, :level=>:error}
:Exception in thread "[main]>worker0" com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.:message=>"JDBC - Exception repeated 
more than the maximum configured", :exception=>com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed., :max_repeat_exceptions=>5,
 :max_repeat_exceptions_time=>30, :level=>:error}

any help ?

Thanks,
Navneet

**Comment by theangryangel** [comment]
The message `No operations allowed after connection closed.` says that the connection via JDBC was closed. This plugin has been using pooled connections since early Logstash v2, so this message should not be possible if the pool is doing it's job correctly. 

What version of logstash and what version of the plugin are you running?

If you're still running Logstash 1.4 or a very old version of Logstash v2, I **highly** recommend upgrading both Logstash and the plugin as there have been numerous fixes and improvements to both the plugin and Logstash.

If you upgrade to a newer version of Logstash v2 you can install the correct version by running `bin/logstash-plugin install --version 0.3.2 logstash-output-jdbc`

**Comment by NavneetMathpal** [comment]
Hi @theangryangel  ,

I am using logstash-2.3.1 , with that using   logstash-output-jdbc_jars.rb and  mysql-connector-java-5.1.36-bin.jar .

I googled this error  and found this - If database remains idle for more than 8 hours it is closed by default.

Thanks,
Navneet

**Comment by theangryangel** [comment]
The pool should be intelligently maintaining multiple connections. It should never be hitting 8 hours if you're on a recent version of the plugin.

Please check your version of the plugin. It sounds like you're on a very very old version.

**Comment by NavneetMathpal** [comment]
@theangryangel  I am using JDBC.rb (latest)+ mysql-connector-java-5.1.36-bin.jar . is it not the accurate version of jar for this ?

**Comment by theangryangel** [comment]
I don't see why the jar would really matter in this instance.

Can you run `bin/logstash-plugin list` and put the output in here, and also provide the jdbc bits from your configuration please?

**Comment by theangryangel** [comment]
If you can provide any further information Navneet I'm willing to look at it. However I can't reproduce this issue on any recent version of Logstash or the plugin. I've got stuff thats literally been connected and functioning for weeks.
