### ISSUE TITLE
Advice on optimization with MS SQL insert

### ISSUE THREAD

**Issue by phr0gz** [theangryangel/logstash-output-jdbc#82]
Hello, I'm now using Logstah 5 and the version 5.2.0 of the logstash jdbc output plugin.

Do you have any recommendation to speed-up the SQL insertion in a table with a PK (with a clustered index) which is set to auto increment to +1 for each new raw ?

With the default plugin settings, there are always 2-4 SUSPENDED queries (wait type:WRITELOG). Logstash is set to use 24 worker threads.

Is there a way to avoid those suspended queries?

Thanks

**Comment by theangryangel** [comment]
Suspended (type: writelog) queries are usually due to your SQL server storage not keeping up with demand. Depending on your insert query, the table, the storage and indexing, it might just be a sizing issue.

The plugin will be throwing stuff at your SQL server as fast as it can. You can probably slow it down by reducing the number of workers, but you'll end up creating a back log...

**Comment by phr0gz** [comment]
So some news: we have tried to analyse the issue a little bit more, the sql server is "normally" able to handle a heavy load (san with some ssd, 200 Gigs of ram....). But as I can see every 20 minutes the server is sending logs only to some databases. And only after the 20 minutes  there is a retry with a huge volume of data during 10 minutes and the SQL server is eating more than 1500 Batch Requests/sec...
There are some disk queue spikes during this 10 minutes, but after that no queue during the next 20 minutes.

**Logstash server info:** 
Is runing between 25 and 50% of cpu, it's a 10 cores VM with 25 worker threads in logstash. 
About the CPU: 25 % during 20 minutes and 50 % during 10 minutes

**Comment by theangryangel** [comment]
> After 20 minutes there is a retry with a huge volume of data during 10 minutes

As in a huge retry of events that aren't going through because of insertion/update/whatever failure(s)? If you look at the logs for logstash (or use sql server profiler) you should be able to see the exception... 

The plugin should **only** be retrying [these](https://github.com/theangryangel/logstash-output-jdbc/blob/master/lib/logstash/outputs/jdbc.rb#L20) exceptions codes. It could be one of them isn't actually retry-able in your case. In which case the right fix is to either configure your logstash to drop these broken events in a filter before they get to the jdbc output, or we can look at removing the exception code from the retry list...

**Comment by phr0gz** [comment]
I will close and conclude: In fact it was because of logstash, it will not use 100 of the cpu even if he is overloaded (actually I'm using 75% max with 12 cpu).
Sorry for the waste of time :)
