### ISSUE TITLE
Output erroneus statement on jdbc exception (warning/error)

### ISSUE THREAD

**Issue by mwohlert** [theangryangel/logstash-output-jdbc#87]
Not an issue rather than an improvement idea for debugging.

I am currently parsing aboud 60GB of logs and sometimes I run into a JDBC - exception. It would be great to have the statement that caused this in the log for debugging purposos, alongside with the exception message. My Idea would be a level limiter in the configuration so ['error', 'warning'] would output the message on both type and ['error'] only when an error occurs.

The general question is: Are you interested in this (should I make a pull request once I implemeted this behavior) or should I keep it in my fork?
I haven't started implementing. Just a question beforehand.

**Comment by theangryangel** [comment]
All PRs are welcome, as long as it doesn't break or change existing functionality :)

**Comment by mwohlert** [comment]
My initial idea is to output the statement in https://github.com/theangryangel/logstash-output-jdbc/blob/master/lib/logstash/outputs/jdbc.rb#L316 

So the statement had to be passed from submit -> retry_exception? -> log_jdbc_exception , where it would be like this:
`@logger.send(log_method, log_text, :exception => current_exception, :statement => current_statement)`

**Comment by theangryangel** [comment]
Sounds good. PR is very welcome for this 👍

**Comment by mwohlert** [comment]
I reused add_statement_event_params for replacing the ? placeholders with the values from the event. Do you have an Idea to reduce the code maybe, because it is basically the same?

https://github.com/mwohlert/logstash-output-jdbc/commit/79dc6a6a4d92635095ad73ed65b958e1f8dae320

**Comment by theangryangel** [comment]
To be honest @mwohlert I probably wouldn't even bother trying to populate the placeholders like that, and instead do like Postgres, SQL Server, etc. do when looking at debug/logging information, and instead display something like this.

`statement="update table set something = ? where id = ?", params=["first param", "second param"]`

Whilst it won't give you a query you can run manually (and I totally understand why you might want to do that - because I've had that need a few times) it does have the benefit of being very clear that it's a prepared statement being run, and no one will accidentally run an SQL injection by copying and pasting the query from the log(s) (I actually had a client do this recently, so I'm acutely aware this does happen).

**Comment by theangryangel** [comment]
2bdb75f1b762e2ea481354337a08cc75632bbc9f sort of deals with this. It's not ideal, but a step in the right direction.
