### ISSUE TITLE
cannot link Java class com .zaxxer.hikari.HikariDataSource

### ISSUE THREAD

**Issue by arokiabhavya** [theangryangel/logstash-output-jdbc#89]
Hi,
* Version of Logstash used:  5.3.2
* Database engine & version you're connecting to: oracle 11g
Recieved the below error while starting logstash eventhough ojdbc6.jar,HikariCP 2.6.1 & sl4j-impl 2.6.2 
@output_class=LogStash::Outputs::Jdbc>", :error=>"**cannot link Java class com
.zaxxer.hikari.HikariDataSource, probable missing dependency: org/slf4j/LoggerFa
ctory"}**
09:52:23.281 [[main]-pipeline-manager] ERROR logstash.agent - Pipeline aborted d
ue to error {:exception=>#<NameError: cannot link Java class com.zaxxer.hikari.H
ikariDataSource, probable missing dependency: org/slf4j/LoggerFactory>, :backtra

Thanks 

## Your Environment

* Version of plugin used: 
* Version of Logstash used:  
* Database engine & version you're connecting to: 
* Have you checked you've met the Logstash requirements for Java versions?:

**Comment by theangryangel** [comment]
What version of the plugin are you using please? Latest? Or something older? Did you install it via the logstash-plugin command (please tell me you didn't just clone the repo/download it as a zip).

I've not yet had the time to test Logstsh 5.3 myself, but

**Comment by arokiabhavya** [comment]
We downloaded the master version as a zip,edited gem file as **gem "logstash-output-jdbc", :Path => "./logstash-output-jdbc"** and installed **logstash-plugin install --no-verify**
Can you please give the log-stash version in which you have tested?
And can you give the list of jars to be placed in vendor/jdbc/jar?

**Comment by theangryangel** [comment]
> We downloaded the master version as a zip

I would not suggest doing that, since you're just creating more work for yourself and me. Just use the logstash-plugin command.

If there is some reason you can't use the logstash-plugin command, then you need the jars and their dependencies listed in https://github.com/theangryangel/logstash-output-jdbc/blob/master/logstash-output-jdbc.gemspec#L29

You can either install them by hand, or use `rake install_jars` task from the Rakefile.
